project_id = "ehykqgttaoigscroafpu"

[functions.entretien-chat]
verify_jwt = false

[functions.math-chat]
verify_jwt = false

[functions.verify-answer]
verify_jwt = false

[functions.visualize]
verify_jwt = false